### ISSUE TITLE
Fails to convert "\'i" into "í"

### ISSUE THREAD

**Issue by MLopez-Ibanez** [GeoBosh/rbibutils#7] opened 2021-10-07 19:29 UTC
```bibtex
@misc{x,
author = "P{\'\i}{\'i}"
}
```
```R
rbibutils::readBib("test.bib", direct=TRUE, encoding = "UTF-8")
```
produces:
```
Pí\'i (????).
```
but it should produce:
```
Píí (????).
```

This may be a bug in R itself: https://bugs.r-project.org/show_bug.cgi?id=18208

**Comment by MLopez-Ibanez** [comment] 2021-10-08 07:03
I believe this causes Rdpack to not generate correct output as can be seen in the references of this page: https://mlopez-ibanez.github.io/eaf/reference/hypervolume.html

**Comment by GeoBosh** [comment] 2021-10-09 09:00
Yes indeed. I am not sure if compensating for R's failure to convert `\'i` is suitable approach. 

I emailed R-devel with a suggestion of how to fix `\'i` conversion, see https://stat.ethz.ch/pipermail/r-devel/2021-October/081150.html . If they give me access to bugzilla I will try to submit a patch. Feel free to do it yourself if you wish.

**Comment by GeoBosh** [comment] 2021-10-10 08:40
Now at least the option to use `\'\i` is retained until/if `\'i` is fixed in R. I will think if a quick patch could be implemented for Rdpack to deal with this in the mean time.

**Comment by GeoBosh** [comment] 2021-12-08 08:23
I updated  Rdpack and rbibutils on CRAN. This should resolve all problems discussed in this issue.

**Comment by EricMarcon** [comment] 2022-12-15 07:07
I'm sorry to reopen this issue but Rdpack fails when the _journal_ field contains `\'i`.

I have a reference with `journal = {Qu\'imica Nova}`. When checking the package (I run `devtools::check()`) with Rdpack 2.4 and rbibutils 2.2.9, I get a (funny) warning:
> Warning in parse_Rd(tmpcon, encoding = "UTF-8", fragment = TRUE, macros = macros) :
     <connection>:3: unknown macro '\imicaNova'

The reference in the help page reads: 
`Tsallis C (1994). “What Are the Numbers That Experiments Provide?” Qu\'\imicaNova, 17(6), 468–471.`

A workaround is to brace-protect the character: `{\'i}` is converted with no issue. The developer of Better BibTeX accepted [to add an option](https://github.com/retorquere/zotero-better-bibtex/issues/2337) so that automatic exports from Zotero can be brace-protected, but the optimal solution seems to be to extend the patch for Rdpack to all text fields, including journal beyond author and editor.

**Comment by GeoBosh** [comment] 2022-12-15 08:27
Thanks for the report. It is certainly a bug in Rdpack (or more likely in rbibutils parser, but that's my concern) that should be fixed. Could you provide the full bib entry for this reference?

**Comment by EricMarcon** [comment] 2022-12-15 09:11
Sure:
```
@article{Tsallis1994,
  title = {What Are the Numbers That Experiments Provide?},
  author = {Tsallis, Constantino},
  year = {1994},
  journal = {Qu\'imica Nova},
  volume = {17},
  number = {6},
  pages = {468--471}
}
```

If this can help, I can see the issue is from argument `texChars` in `readBib()` :
```
rbibutils::readBib(file = "inst/REFERENCES.bib", encoding = "UTF-8", direct = TRUE, texChars = "Rdpack")
## Tsallis C (1994). “What Are the Numbers That Experiments Provide?”
_Qu\'\imicaNova_, *17*(6), 468-471.
```
but ` texChars = "convert"` is OK:
```
rbibutils::readBib(file = "inst/REFERENCES.bib", encoding = "UTF-8", direct = TRUE, texChars = "convert")
## Tsallis C (1994). “What Are the Numbers That Experiments Provide?” _Química Nova_,
*17*(6), 468-471..
```
The argument comes from `Rdpack::get_bibentries()`:
```
res <- if (packageVersion("rbibutils") > "2.2.4") 
        readBib(file = fn, encoding = encoding, direct = TRUE, 
            texChars = "Rdpack")
    else if (packageVersion("rbibutils") >= "2.1.2") 
        readBib(file = fn, encoding = encoding, direct = TRUE)
```
A quick solution to my issue would be to use `texChars = "convert"` instead of `texChars = "Rdpack"` but I guess this is not so simple.

**Comment by GeoBosh** [comment] 2022-12-15 11:58
Thanks for the detailed analysis. 

Indeed, `texChars = "convert"` has its own problems. On Windows that could be problematic when a symbol was not available in the current codepage (though this is no longer a problem for R since R 4.2.0). Also, some UTF-8 characters are not setup in LaTeX leading to errors when building the pdf manual. For plain text this is (rarely) a problem though. 

Let me note that you have strong case to ask at least for an option to put braces around accented characters in bibtex files, since this is the recommended way to input them. Also, if they don't put braces around such characters in 'Author' field and similar this may result in wrong alphabetical sorting. It is even possible to get curious errors from bibtex in certain circumstances. For example,
`publisher = "Birkh\"auser"` may well throw error due to unmatched.

While writing the above, I recalled why I didn't do the same fix at the time for other fields. Partly it was lack of time. But the main reason was that it needs careful thought for unintended side effects. For example is
In truth, for `\' x` and similar, it looks that side effects are not likely.

**Comment by GeoBosh** [comment] 2022-12-15 20:21
I uploaded `rbibutils` containing a draft fix for `\'` escaped characters. You can install it from github as usual:
```
install_github("GeoBosh/rbibutils")
```
I modified your example to check that no superfluous braces appear when `\'i` is already in braces:
```
@article{Tsallis1994,
  title = {What Are the Numbers That Experiments Provide?},
  author = {Tsallis, Constantino},
  year = {1994},
  journal = {Qu\'imica Nova and already braced Qu{\'i}mica},
  volume = {17},
  number = {6},
  pages = {468--471}
}
```
With the updated `rbibutils` I now get
```
> readBib("Org/bug7_reopened_EricMarcon.bib", direct = TRUE, texChars = "Rdpack")
Tsallis C (1994). “What Are the Numbers That Experiments Provide?”
_Química Nova and already braced Química_, *17*(6), 468-471.
```
It seems to work although before submitting to CRAN I need to do comprehensive tests and reverse dependencies checks for Rdpack.

**Comment by GeoBosh** [comment] 2022-12-16 14:14
For future reference, I will summarise the problem since initially I didn't realise what caused it.

Since the R function that converts LaTeX characters to ordinary characters supports `\'\i` but not `\'i` rbibutils converts the latter to the former when called with `texChars = "Rdpack" (i.e., this does not affect the user  facing options for `texChars`. This introduced the possibility valid input to cause errors, in that the conversion turns `fgh\'ijkl` to `fgh\'\ijkl`, which contains the unintended LaTeX command `\ijkl`. I fixed this for Author and similar fields bot not for others. So the bug was lingering around to catch somebody.

**Closed** 2023-01-11 16:35 UTC
